# 넘파이(NumPy) - 배열 객체 다루기

In [1]:
import numpy as np
test_array = np.array([1, 4, 5, 8], float)
test_array

array([1., 4., 5., 8.])

In [2]:
type(test_array[3])

numpy.float64

In [3]:
test_array = np.array([1, 4, 5, "8"], float)
test_array

array([1., 4., 5., 8.])

In [4]:
type(test_array[3])

numpy.float64

In [5]:
test_array.dtype #배열 전체의 데이터 타입 반환

dtype('float64')

In [6]:
test_array.shape #배열의 구조(shape) 반환

(4,)

In [7]:
matrix = [[1,2,5,8], [1,2,5,8], [1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

In [8]:
tensor_rank3 = [
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
]
np.array(tensor_rank3, int).shape

(4, 3, 4)

In [9]:
np.array(tensor_rank3, int).ndim

3

In [10]:
np.array(tensor_rank3, int).size

48

In [11]:
np.array( [ [1, 2, 3.5], [4, 5, 6.5]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.array( [ [1, 2, 3.5], [4, 5, 6.5]], dtype=float)

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [13]:
import sys
np.array( [[1, 2, 3.5], [4, 5, 6.5]], dtype=np.float64).itemsize

8

In [14]:
np.array( [[1, 2, 3.5], [4, 5, 6.5]], dtype=np.float32).itemsize

4

In [15]:
x = np.array([[1, 2, 5, 8], [1, 2, 5, 8]])
x.shape

(2, 4)

In [16]:
x.reshape(2,2)

In [17]:
x.reshape(4,2)

array([[1, 2],
       [5, 8],
       [1, 2],
       [5, 8]])

In [18]:
x = np.array(range(8)).reshape(4,2)
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [19]:
x.reshape(2,-1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [20]:
x.reshape(2,2,-1)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [21]:
x.reshape(-1,)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [22]:
x = np.array(range(8)).reshape(2,2,2)
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [23]:
x.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [24]:
x = np.array([[1, 2, 3], [4.5, 5, 6]], int)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
x[0][0]

1

In [26]:
x[0,2]

3

In [27]:
x[0, 1] = 100
x

array([[  1, 100,   3],
       [  4,   5,   6]])

In [28]:
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
x[:,2:] #전체 행의 2열 이상

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [29]:
x[1,1:3] #1행의 1열 ~ 2열

array([7, 8])

In [30]:
x[1:3] #1행 ~ 2행의 전체

array([[ 6,  7,  8,  9, 10]])

In [31]:
x = np.array(range(15), int).reshape(3, -1)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
x[:,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [33]:
x[::2,::3]

array([[ 0,  3],
       [10, 13]])

In [34]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(-5, 5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [36]:
np.arange(0, 5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [37]:
np.ones(shape=(5,2), dtype=np.int8)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [38]:
np.zeros(shape=(2,2), dtype=np.float32)

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [39]:
np.empty(shape=(2,4), dtype=np.float32)

array([[0.    , 1.875 , 0.    , 2.25  ],
       [0.    , 2.3125, 0.    , 2.5   ]], dtype=float32)

In [40]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
np.ones_like(x)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [42]:
np.zeros_like(x)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [43]:
np.empty_like(x)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [44]:
np.identity(n=3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [45]:
np.identity(n=4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [46]:
np.eye(N=3, M=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [47]:
np.eye(N=3, M=5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [48]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
np.diag(matrix)

array([0, 4, 8])

In [50]:
np.diag(matrix, k=1)

array([1, 5])

In [51]:
np.random.uniform(0, 5, 10)

array([2.22367616, 2.8286466 , 4.35935841, 0.21897672, 4.61329179,
       3.81520245, 1.34739281, 0.65992621, 3.03299715, 4.97364063])

In [52]:
np.random.normal(0, 2, 10)

array([ 0.05124111, -1.08882446, -1.07086545, -4.45826838,  3.78724076,
       -0.95802436, -1.15427134, -0.92596507,  0.12089848, -1.84587299])